flags: {}
extra-package-dbs: []
packages:
- '.'
- location:
    git: git@github.com:lialan/llvm-general.git
    commit: c4c26408ac6b32555678f7bd91972bb5adaee137
  subdirs:
  - llvm-general-pure
resolver: lts-8.5
